name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
     #   cache: gradle

    - name: Grant execute permission for gradle
      run: chmod +x gradle
    - name: Build with Gradle
      run: ./gradle build
